# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from myo_raw/EMGData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EMGData(genpy.Message):
  _md5sum = "cacb00d78b8d8a4ba46dcd469cd1cda3"
  _type = "myo_raw/EMGData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Provides access to the raw emg data off the sensor
# Useful to try and write your own classifier


# The raw sensor reading off of each of the 8 emg sensors
# note this reading is dependent on the rotation of the sensor
# on the arm
uint32[8] emg_data

# Was the sensor moving during this reading
bool     moving
"""
  __slots__ = ['emg_data','moving']
  _slot_types = ['uint32[8]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       emg_data,moving

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EMGData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.emg_data is None:
        self.emg_data = [0,0,0,0,0,0,0,0]
      if self.moving is None:
        self.moving = False
    else:
      self.emg_data = [0,0,0,0,0,0,0,0]
      self.moving = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_8I.pack(*self.emg_data))
      buff.write(_struct_B.pack(self.moving))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 32
      self.emg_data = _struct_8I.unpack(str[start:end])
      start = end
      end += 1
      (self.moving,) = _struct_B.unpack(str[start:end])
      self.moving = bool(self.moving)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.emg_data.tostring())
      buff.write(_struct_B.pack(self.moving))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 32
      self.emg_data = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=8)
      start = end
      end += 1
      (self.moving,) = _struct_B.unpack(str[start:end])
      self.moving = bool(self.moving)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_8I = struct.Struct("<8I")
