# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from myo_raw/MyoArm.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MyoArm(genpy.Message):
  _md5sum = "ef98f3b0198c2ce3840df4d4d22e916b"
  _type = "myo_raw/MyoArm"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """## A MyoArm message can be used to determine the last known
## arm the myo was determined to be on (only sent for API version 1+)

int32 ARM_UNKNOWN = 0
int32 ARM_RIGHT = 1
int32 ARM_LEFT = 2

int32 XDIR_UNKNOWN = 0
int32 XDIR_TOWARD_WRIST = 1
int32 XDIR_TOWARD_ELBOW = 2


# Which arm is the myo currently on
int32 arm

# What is the determined x direction (is is the light up or down)
# In other words is the light pointing up or down?
int32 xdir"""
  # Pseudo-constants
  ARM_UNKNOWN = 0
  ARM_RIGHT = 1
  ARM_LEFT = 2
  XDIR_UNKNOWN = 0
  XDIR_TOWARD_WRIST = 1
  XDIR_TOWARD_ELBOW = 2

  __slots__ = ['arm','xdir']
  _slot_types = ['int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm,xdir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MyoArm, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm is None:
        self.arm = 0
      if self.xdir is None:
        self.xdir = 0
    else:
      self.arm = 0
      self.xdir = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.arm, _x.xdir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.arm, _x.xdir,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.arm, _x.xdir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.arm, _x.xdir,) = _struct_2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i = struct.Struct("<2i")
